org: fischernz
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}

package: 
  individually: true

build: 
  esbuild: 
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/lambdas/signin.handler
    events:
      - httpApi:
          path: /signin
          method: post
  
  signup:
    handler: src/lambdas/signup.handler
    events:
      - httpApi:
          path: /signup
          method: post
  
  me:
    handler: src/lambdas/me.handler
    events:
      - httpApi:
          path: /me
          method: get
  
  createMeal:
    handler: src/lambdas/createMeal.handler
    events:
      - httpApi:
          path: /meals
          method: post

  listMeal:
    handler: src/lambdas/listMeal.handler
    events:
      - httpApi:
          path: /meals
          method: get

  getMealById:
    handler: src/lambdas/getMealById.handler
    events:
      - httpApi:
          path: /meals/{mealId}
          method: get
